// Code generated by go-swagger; DO NOT EDIT.

package products

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"swagger/models"
)

// NoParamReader is a Reader for the NoParam structure.
type NoParamReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *NoParamReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewNoParamOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewNoParamBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /] noParam", response, response.Code())
	}
}

// NewNoParamOK creates a NoParamOK with default headers values
func NewNoParamOK() *NoParamOK {
	return &NoParamOK{}
}

/*
NoParamOK describes a response with status code 200, with default header values.

NoParamOK no param o k
*/
type NoParamOK struct {
	Payload []*models.Product
}

// IsSuccess returns true when this no param o k response has a 2xx status code
func (o *NoParamOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this no param o k response has a 3xx status code
func (o *NoParamOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this no param o k response has a 4xx status code
func (o *NoParamOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this no param o k response has a 5xx status code
func (o *NoParamOK) IsServerError() bool {
	return false
}

// IsCode returns true when this no param o k response a status code equal to that given
func (o *NoParamOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the no param o k response
func (o *NoParamOK) Code() int {
	return 200
}

func (o *NoParamOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /][%d] noParamOK %s", 200, payload)
}

func (o *NoParamOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /][%d] noParamOK %s", 200, payload)
}

func (o *NoParamOK) GetPayload() []*models.Product {
	return o.Payload
}

func (o *NoParamOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewNoParamBadRequest creates a NoParamBadRequest with default headers values
func NewNoParamBadRequest() *NoParamBadRequest {
	return &NoParamBadRequest{}
}

/*
NoParamBadRequest describes a response with status code 400, with default header values.

NoParamBadRequest no param bad request
*/
type NoParamBadRequest struct {
	Payload *models.ValidationError
}

// IsSuccess returns true when this no param bad request response has a 2xx status code
func (o *NoParamBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this no param bad request response has a 3xx status code
func (o *NoParamBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this no param bad request response has a 4xx status code
func (o *NoParamBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this no param bad request response has a 5xx status code
func (o *NoParamBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this no param bad request response a status code equal to that given
func (o *NoParamBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the no param bad request response
func (o *NoParamBadRequest) Code() int {
	return 400
}

func (o *NoParamBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /][%d] noParamBadRequest %s", 400, payload)
}

func (o *NoParamBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /][%d] noParamBadRequest %s", 400, payload)
}

func (o *NoParamBadRequest) GetPayload() *models.ValidationError {
	return o.Payload
}

func (o *NoParamBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ValidationError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
